In [14]:
import numpy as np
print(np.__version__)

2.0.1


In [41]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
even_numbers = a[a % 2 == 0]
print(even_numbers)

[ 2  4  6  8 10 12 14]


In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_value = np.mean(a)
print(mean_value)

5.5


In [42]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a % 2 != 0
print(b)

[ True False  True False  True False  True False  True False]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  
b = a.reshape(3, 4)  
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [37]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[1, :]
print(b)  

[4 5 6]


In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a + 1  
print(b)

[[2 3 4]
 [5 6 7]]


In [45]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([4, 5])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 6]


In [58]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a == b)[0]
print(result)

[1 3 5 7]


In [32]:
import numpy as np
data = np.genfromtxt('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv', delimiter=',', dtype=None, encoding='utf-8', skip_header=1, names=True)
print(data[:3])

[(0.21, '"Premium"', '"E"', '"SI1"', 59.8, 61., 326, 3.89, 3.84, 2.31)
 (0.23, '"Good"', '"E"', '"VS1"', 56.9, 65., 327, 4.05, 4.07, 2.31)
 (0.29, '"Premium"', '"I"', '"VS2"', 62.4, 58., 334, 4.2 , 4.23, 2.63)]


In [20]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv"
diamonds = pd.read_csv(url)
print(diamonds.head(10))

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39


In [26]:
cut_series = diamonds['cut']
print(cut_series)

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...    
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: object


In [27]:
quality_merge = diamonds['cut'] + '-' + diamonds['color']
diamonds['Quality-merge'] = quality_merge
print(diamonds['Quality-merge'])

0            Ideal-E
1          Premium-E
2             Good-E
3          Premium-I
4             Good-J
            ...     
53935        Ideal-D
53936         Good-D
53937    Very Good-D
53938      Premium-H
53939        Ideal-D
Name: Quality-merge, Length: 53940, dtype: object


In [28]:
rows, columns = diamonds.shape
dtypes = diamonds.dtypes
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")
print("Datatypes of each column:")
print(dtypes)


Number of rows: 53940
Number of columns: 11
Datatypes of each column:
carat            float64
cut               object
color             object
clarity           object
depth            float64
table            float64
price              int64
x                float64
y                float64
z                float64
Quality-merge     object
dtype: object


In [29]:
object_summary = diamonds.select_dtypes(include=['object']).describe()
print(object_summary)

          cut  color clarity Quality-merge
count   53940  53940   53940         53940
unique      5      7       8            35
top     Ideal      G     SI1       Ideal-G
freq    21551  11292   13065          4884


In [30]:
missing_values = diamonds.isnull().sum()
print(missing_values)

carat            0
cut              0
color            0
clarity          0
depth            0
table            0
price            0
x                0
y                0
z                0
Quality-merge    0
dtype: int64


In [31]:
diamonds_dropped_any = diamonds.dropna(subset=['cut', 'color'], how='any')
diamonds_dropped_all = diamonds.dropna(subset=['cut', 'color'], how='all')
print("DataFrame after dropping rows with any missing values in 'cut' or 'color':")
print(diamonds_dropped_any)
print("DataFrame after dropping rows with all missing values in 'cut' or 'color':")
print(diamonds_dropped_all)

DataFrame after dropping rows with any missing values in 'cut' or 'color':
       carat        cut color clarity  depth  table  price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2 